### ISSUE TITLE
psycopg2.ProgrammingError: relation "pgcontents.users" does not exist

### ISSUE THREAD

**Issue by hol-42** [pl31/heroku-jupyter#16] opened 2017-05-09 06:37 UTC
Installed on Heroku. Apparently an error when accessing DB. Please see the full log

```
2017-05-09T06:31:28.563738+00:00 app[web.1]: [I 06:31:28 InstallContribNbextensionsApp] Making directory: /app/.local/share/jupyter/nbextensions/latex_envs/doc/latex_env_doc_files
2017-05-09T06:31:28.563962+00:00 app[web.1]: [I 06:31:28 InstallContribNbextensionsApp] Copying: /app/.conda/lib/python3.6/site-packages/latex_envs/static/doc/latex_env_doc_files/latex_env_doc_41_0.png -> /app/.local/share/jupyter/nbextensions/latex_envs/doc/latex_env_doc_files/latex_env_doc_41_0.png
2017-05-09T06:31:28.564434+00:00 app[web.1]: [I 06:31:28 InstallContribNbextensionsApp] Copying: /app/.conda/lib/python3.6/site-packages/latex_envs/static/doc/latex_env_doc_files/latex_env_doc_51_0.png -> /app/.local/share/jupyter/nbextensions/latex_envs/doc/latex_env_doc_files/latex_env_doc_51_0.png
2017-05-09T06:31:28.564962+00:00 app[web.1]: [I 06:31:28 InstallContribNbextensionsApp] Copying: /app/.conda/lib/python3.6/site-packages/latex_envs/static/doc/latex_env_doc_files/latex_env_doc_49_0.png -> /app/.local/share/jupyter/nbextensions/latex_envs/doc/latex_env_doc_files/latex_env_doc_49_0.png
2017-05-09T06:31:28.565504+00:00 app[web.1]: [I 06:31:28 InstallContribNbextensionsApp] Copying: /app/.conda/lib/python3.6/site-packages/latex_envs/static/doc/latex_env_doc_files/latex_env_doc_42_0.png -> /app/.local/share/jupyter/nbextensions/latex_envs/doc/latex_env_doc_files/latex_env_doc_42_0.png
2017-05-09T06:31:28.566001+00:00 app[web.1]: [I 06:31:28 InstallContribNbextensionsApp] Copying: /app/.conda/lib/python3.6/site-packages/latex_envs/static/doc/latex_env_doc_files/latex_env_doc_27_2.png -> /app/.local/share/jupyter/nbextensions/latex_envs/doc/latex_env_doc_files/latex_env_doc_27_2.png
2017-05-09T06:31:28.566509+00:00 app[web.1]: [I 06:31:28 InstallContribNbextensionsApp] Copying: /app/.conda/lib/python3.6/site-packages/latex_envs/static/doc/latex_env_doc_files/latex_env_doc_46_0.png -> /app/.local/share/jupyter/nbextensions/latex_envs/doc/latex_env_doc_files/latex_env_doc_46_0.png
2017-05-09T06:31:28.566998+00:00 app[web.1]: [I 06:31:28 InstallContribNbextensionsApp] Copying: /app/.conda/lib/python3.6/site-packages/latex_envs/static/doc/latex_env_doc_files/latex_env_doc_45_0.png -> /app/.local/share/jupyter/nbextensions/latex_envs/doc/latex_env_doc_files/latex_env_doc_45_0.png
2017-05-09T06:31:28.567507+00:00 app[web.1]: [I 06:31:28 InstallContribNbextensionsApp] Copying: /app/.conda/lib/python3.6/site-packages/latex_envs/static/doc/latex_env_doc_files/latex_env_doc_26_2.png -> /app/.local/share/jupyter/nbextensions/latex_envs/doc/latex_env_doc_files/latex_env_doc_26_2.png
2017-05-09T06:31:28.568034+00:00 app[web.1]: [I 06:31:28 InstallContribNbextensionsApp] Copying: /app/.conda/lib/python3.6/site-packages/latex_envs/static/doc/latex_env_doc_files/latex_env_doc_50_0.png -> /app/.local/share/jupyter/nbextensions/latex_envs/doc/latex_env_doc_files/latex_env_doc_50_0.png
2017-05-09T06:31:28.568565+00:00 app[web.1]: [I 06:31:28 InstallContribNbextensionsApp] Copying: /app/.conda/lib/python3.6/site-packages/latex_envs/static/doc/latex_env_doc_files/latex_env_doc_43_0.png -> /app/.local/share/jupyter/nbextensions/latex_envs/doc/latex_env_doc_files/latex_env_doc_43_0.png
2017-05-09T06:31:28.569079+00:00 app[web.1]: [I 06:31:28 InstallContribNbextensionsApp] Copying: /app/.conda/lib/python3.6/site-packages/latex_envs/static/doc/latex_env_doc_files/latex_env_doc_44_0.png -> /app/.local/share/jupyter/nbextensions/latex_envs/doc/latex_env_doc_files/latex_env_doc_44_0.png
2017-05-09T06:31:28.569572+00:00 app[web.1]: [I 06:31:28 InstallContribNbextensionsApp] Copying: /app/.conda/lib/python3.6/site-packages/latex_envs/static/doc/latex_env_doc_files/latex_env_doc_47_0.png -> /app/.local/share/jupyter/nbextensions/latex_envs/doc/latex_env_doc_files/latex_env_doc_47_0.png
2017-05-09T06:31:28.570104+00:00 app[web.1]: [I 06:31:28 InstallContribNbextensionsApp] Copying: /app/.conda/lib/python3.6/site-packages/latex_envs/static/doc/latex_env_doc_files/latex_env_doc_23_2.png -> /app/.local/share/jupyter/nbextensions/latex_envs/doc/latex_env_doc_files/latex_env_doc_23_2.png
2017-05-09T06:31:28.570621+00:00 app[web.1]: [I 06:31:28 InstallContribNbextensionsApp] Copying: /app/.conda/lib/python3.6/site-packages/latex_envs/static/doc/latex_env_doc_files/latex_env_doc_52_0.png -> /app/.local/share/jupyter/nbextensions/latex_envs/doc/latex_env_doc_files/latex_env_doc_52_0.png
2017-05-09T06:31:28.571170+00:00 app[web.1]: [I 06:31:28 InstallContribNbextensionsApp] Copying: /app/.conda/lib/python3.6/site-packages/latex_envs/static/doc/latex_env_doc_files/latex_env_doc_48_0.png -> /app/.local/share/jupyter/nbextensions/latex_envs/doc/latex_env_doc_files/latex_env_doc_48_0.png
2017-05-09T06:31:28.571719+00:00 app[web.1]: [I 06:31:28 InstallContribNbextensionsApp] Copying: /app/.conda/lib/python3.6/site-packages/latex_envs/static/doc/latex_env_doc_files/latex_env_doc_24_2.png -> /app/.local/share/jupyter/nbextensions/latex_envs/doc/latex_env_doc_files/latex_env_doc_24_2.png
2017-05-09T06:31:28.572264+00:00 app[web.1]: [I 06:31:28 InstallContribNbextensionsApp] - Validating: OK
2017-05-09T06:31:28.572968+00:00 app[web.1]: [I 06:31:28 InstallContribNbextensionsApp] Installing jupyter_contrib_nbextensions items to config in /app/.jupyter
2017-05-09T06:31:28.577247+00:00 app[web.1]: Enabling: jupyter_nbextensions_configurator
2017-05-09T06:31:28.577389+00:00 app[web.1]: - Writing config: /app/.jupyter
2017-05-09T06:31:28.577997+00:00 app[web.1]:     - Validating...
2017-05-09T06:31:28.578211+00:00 app[web.1]:       jupyter_nbextensions_configurator  OK
2017-05-09T06:31:28.578358+00:00 app[web.1]: Enabling notebook nbextension nbextensions_configurator/config_menu/main...
2017-05-09T06:31:28.588890+00:00 app[web.1]: [I 06:31:28 InstallContribNbextensionsApp] Enabling notebook extension contrib_nbextensions_help_item/main...
2017-05-09T06:31:28.585798+00:00 app[web.1]: Enabling tree nbextension nbextensions_configurator/tree_tab/main...
2017-05-09T06:31:28.589791+00:00 app[web.1]: [I 06:31:28 InstallContribNbextensionsApp]       - Validating: OK
2017-05-09T06:31:28.590968+00:00 app[web.1]: [I 06:31:28 InstallContribNbextensionsApp] - Editing config: /app/.jupyter/jupyter_nbconvert_config.json
2017-05-09T06:31:28.591109+00:00 app[web.1]: [I 06:31:28 InstallContribNbextensionsApp] --  Configuring nbconvert template path
2017-05-09T06:31:28.591301+00:00 app[web.1]: [I 06:31:28 InstallContribNbextensionsApp] --  Configuring nbconvert preprocessors
2017-05-09T06:31:28.591477+00:00 app[web.1]: [I 06:31:28 InstallContribNbextensionsApp] - Writing config: /app/.jupyter/jupyter_nbconvert_config.json
2017-05-09T06:31:28.591680+00:00 app[web.1]: [I 06:31:28 InstallContribNbextensionsApp] --  Writing updated config file /app/.jupyter/jupyter_nbconvert_config.json
2017-05-09T06:31:30.370547+00:00 app[web.1]: Enabling: jupyter_nbextensions_configurator
2017-05-09T06:31:30.370658+00:00 app[web.1]: - Writing config: /app/.jupyter
2017-05-09T06:31:30.371146+00:00 app[web.1]:     - Validating...
2017-05-09T06:31:30.371286+00:00 app[web.1]:       jupyter_nbextensions_configurator  OK
2017-05-09T06:31:30.371451+00:00 app[web.1]: Enabling notebook nbextension nbextensions_configurator/config_menu/main...
2017-05-09T06:31:30.372707+00:00 app[web.1]: Enabling tree nbextension nbextensions_configurator/tree_tab/main...
2017-05-09T06:31:32.274466+00:00 app[web.1]: [W 06:31:32.274 NotebookApp] server_extensions is deprecated, use nbserver_extensions
2017-05-09T06:31:32.381652+00:00 app[web.1]:   File "/app/.conda/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1182, in _execute_context
2017-05-09T06:31:32.381649+00:00 app[web.1]: Traceback (most recent call last):
2017-05-09T06:31:32.381655+00:00 app[web.1]:   File "/app/.conda/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 470, in do_execute
2017-05-09T06:31:32.381654+00:00 app[web.1]:     context)
2017-05-09T06:31:32.381655+00:00 app[web.1]:     cursor.execute(statement, parameters)
2017-05-09T06:31:32.381656+00:00 app[web.1]: psycopg2.ProgrammingError: relation "pgcontents.users" does not exist
2017-05-09T06:31:32.381657+00:00 app[web.1]: LINE 1: INSERT INTO pgcontents.users (id) VALUES ('heroku')
2017-05-09T06:31:32.381658+00:00 app[web.1]:                     ^
2017-05-09T06:31:32.381659+00:00 app[web.1]: 
2017-05-09T06:31:32.381659+00:00 app[web.1]: 
2017-05-09T06:31:32.381664+00:00 app[web.1]: 
2017-05-09T06:31:32.381660+00:00 app[web.1]: The above exception was the direct cause of the following exception:
2017-05-09T06:31:32.381665+00:00 app[web.1]: Traceback (most recent call last):
2017-05-09T06:31:32.381665+00:00 app[web.1]:   File "/app/.conda/bin/jupyter-notebook", line 6, in <module>
2017-05-09T06:31:32.381666+00:00 app[web.1]:     sys.exit(notebook.notebookapp.main())
2017-05-09T06:31:32.381667+00:00 app[web.1]:   File "/app/.conda/lib/python3.6/site-packages/jupyter_core/application.py", line 267, in launch_instance
2017-05-09T06:31:32.381668+00:00 app[web.1]:   File "/app/.conda/lib/python3.6/site-packages/traitlets/config/application.py", line 657, in launch_instance
2017-05-09T06:31:32.381669+00:00 app[web.1]:   File "<decorator-gen-7>", line 2, in initialize
2017-05-09T06:31:32.381667+00:00 app[web.1]:     return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
2017-05-09T06:31:32.381671+00:00 app[web.1]:     return method(app, *args, **kwargs)
2017-05-09T06:31:32.381671+00:00 app[web.1]:   File "/app/.conda/lib/python3.6/site-packages/notebook/notebookapp.py", line 1294, in initialize
2017-05-09T06:31:32.381672+00:00 app[web.1]:     self.init_configurables()
2017-05-09T06:31:32.381669+00:00 app[web.1]:     app.initialize(argv)
2017-05-09T06:31:32.381670+00:00 app[web.1]:   File "/app/.conda/lib/python3.6/site-packages/traitlets/config/application.py", line 87, in catch_config_error
2017-05-09T06:31:32.381677+00:00 app[web.1]:     log=self.log,
2017-05-09T06:31:32.381673+00:00 app[web.1]:   File "/app/.conda/lib/python3.6/site-packages/notebook/notebookapp.py", line 1038, in init_configurables
2017-05-09T06:31:32.381678+00:00 app[web.1]:   File "/app/.conda/lib/python3.6/site-packages/pgcontents/pgmanager.py", line 93, in __init__
2017-05-09T06:31:32.381679+00:00 app[web.1]:     super(PostgresContentsManager, self).__init__(*args, **kwargs)
2017-05-09T06:31:32.381679+00:00 app[web.1]:   File "/app/.conda/lib/python3.6/site-packages/pgcontents/managerbase.py", line 66, in __init__
2017-05-09T06:31:32.381680+00:00 app[web.1]:     self.ensure_user()
2017-05-09T06:31:32.381681+00:00 app[web.1]:   File "/app/.conda/lib/python3.6/site-packages/pgcontents/managerbase.py", line 70, in ensure_user
2017-05-09T06:31:32.381681+00:00 app[web.1]:     ensure_db_user(db, self.user_id)
2017-05-09T06:31:32.381682+00:00 app[web.1]:   File "/app/.conda/lib/python3.6/site-packages/pgcontents/query.py", line 89, in ensure_db_user
2017-05-09T06:31:32.381683+00:00 app[web.1]:     users.insert().values(id=user_id),
2017-05-09T06:31:32.381684+00:00 app[web.1]:     return meth(self, multiparams, params)
2017-05-09T06:31:32.381683+00:00 app[web.1]:   File "/app/.conda/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 945, in execute
2017-05-09T06:31:32.381684+00:00 app[web.1]:   File "/app/.conda/lib/python3.6/site-packages/sqlalchemy/sql/elements.py", line 263, in _execute_on_connection
2017-05-09T06:31:32.381686+00:00 app[web.1]:   File "/app/.conda/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1053, in _execute_clauseelement
2017-05-09T06:31:32.381685+00:00 app[web.1]:     return connection._execute_clauseelement(self, multiparams, params)
2017-05-09T06:31:32.381687+00:00 app[web.1]:     compiled_sql, distilled_params
2017-05-09T06:31:32.381689+00:00 app[web.1]:   File "/app/.conda/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1402, in _handle_dbapi_exception
2017-05-09T06:31:32.381687+00:00 app[web.1]:   File "/app/.conda/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1189, in _execute_context
2017-05-09T06:31:32.381688+00:00 app[web.1]:     context)
2017-05-09T06:31:32.381689+00:00 app[web.1]:     exc_info
2017-05-09T06:31:32.381690+00:00 app[web.1]:     reraise(type(exception), exception, tb=exc_tb, cause=cause)
2017-05-09T06:31:32.381690+00:00 app[web.1]:   File "/app/.conda/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
2017-05-09T06:31:32.381691+00:00 app[web.1]:   File "/app/.conda/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 186, in reraise
2017-05-09T06:31:32.381695+00:00 app[web.1]: LINE 1: INSERT INTO pgcontents.users (id) VALUES ('heroku')
2017-05-09T06:31:32.381696+00:00 app[web.1]:                     ^
2017-05-09T06:31:32.381692+00:00 app[web.1]:   File "/app/.conda/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1182, in _execute_context
2017-05-09T06:31:32.381697+00:00 app[web.1]:  [SQL: 'INSERT INTO pgcontents.users (id) VALUES (%(id)s)'] [parameters: {'id': 'heroku'}]
2017-05-09T06:31:32.381693+00:00 app[web.1]:     context)
2017-05-09T06:31:32.381695+00:00 app[web.1]: sqlalchemy.exc.ProgrammingError: (psycopg2.ProgrammingError) relation "pgcontents.users" does not exist
2017-05-09T06:31:32.381691+00:00 app[web.1]:     raise value.with_traceback(tb)
2017-05-09T06:31:32.381694+00:00 app[web.1]:   File "/app/.conda/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 470, in do_execute
2017-05-09T06:31:32.381694+00:00 app[web.1]:     cursor.execute(statement, parameters)
2017-05-09T06:31:32.613651+00:00 heroku[web.1]: Process exited with status 1
2017-05-09T06:31:32.624275+00:00 heroku[web.1]: State changed from starting to crashed
2017-05-09T06:31:33.022150+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=hol42-jupyter.herokuapp.com request_id=5b2eb935-4c17-4ec8-984a-685fea921330 fwd="46.140.136.237" dyno= connect= service= status=503 bytes= protocol=https
2017-05-09T06:31:33.932917+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=hol42-jupyter.herokuapp.com request_id=dba66120-9937-4ac0-992c-c895fbc6d9d6 fwd="46.140.136.237" dyno= connect= service= status=503 bytes= protocol=https
2017-05-09T06:33:06.314226+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=hol42-jupyter.herokuapp.com request_id=7d34abfb-bb09-4e52-911d-78cb82af7504 fwd="46.140.136.237" dyno= connect= service= status=503 bytes= protocol=https
2017-05-09T06:33:07.254966+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=hol42-jupyter.herokuapp.com request_id=e672f5e4-afd3-4c49-bc49-2249bfe67db0 fwd="46.140.136.237" dyno= connect= service= status=503 bytes= protocol=https

```

**Comment by pl31** [comment] 2017-05-09 18:39
Duplicate of #14, even if not obvious. I was not yet able to find a stable configuration in my environment.yml :(. Dependency management is a pain.

**Comment by pl31** [comment] 2017-05-09 20:04
The branch fix-16 will install and run jupyter. Sad enough storing documents does not seem to work reliable.

Writing and maintaining a ContentManager seems to be rather difficult as jupyter interface is a moving target :-1:.

**Closed as completed** 2017-05-09 20:15 UTC
