### ISSUE TITLE
notebook package not found

### ISSUE THREAD

**Issue by Tzikas** [pl31/heroku-jupyter#35] opened 2019-07-16 16:28 UTC
I'm getting this error  in my heroku dashboard after forking and clicking deploy.

```
ResolvePackageNotFound: 
  - notebook=4
 !     Push rejected, failed to compile Python app.
 !     Push failed
```

**Comment by pl31** [comment] 2020-03-06 19:01
Duplicate of #38 

Still no working fix, yet.

**Closed as completed by pl31** 2020-03-06 19:01 UTC
